"""Add Testing status to StatusEnum

Revision ID: 2794fe3a193b
Revises: 72c07a422f5a
Create Date: 2026-05-28 07:48:52.296401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2794fe3a193b'
down_revision = '72c07a422f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
