"""add github linkage to project and task

Revision ID: ab025a305c3e
Revises: d64135d4b0e4
Create Date: 2026-08-24 11:58:18.917374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab025a305c3e'
down_revision = 'd64135d4b0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_repo', sa.String(length=200), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_issue_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('github_pr_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('github_pr_number')
        batch_op.drop_column('github_issue_number')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('github_repo')

    # ### end Alembic commands ###
