"""Add repetitive statuses to StatusEnum

Revision ID: d64135d4b0e4
Revises: 2794fe3a193b
Create Date: 2026-06-13 23:49:21.465698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd64135d4b0e4'
down_revision = '2794fe3a193b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'TESTING', 'DONE', 'BLOCKED', 'REPEAT_DAILY', 'REPEAT_WEEKLY', 'REPEAT_MONTHLY', name='statusenum'),
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('TODO', 'IN_PROGRESS', 'TESTING', 'DONE', 'BLOCKED', 'REPEAT_DAILY', 'REPEAT_WEEKLY', 'REPEAT_MONTHLY', name='statusenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'TESTING', 'DONE', 'BLOCKED', 'REPEAT_DAILY', 'REPEAT_WEEKLY', 'REPEAT_MONTHLY', name='statusenum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('TODO', 'IN_PROGRESS', 'TESTING', 'DONE', 'BLOCKED', 'REPEAT_DAILY', 'REPEAT_WEEKLY', 'REPEAT_MONTHLY', name='statusenum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###
