"""add github review state to task

Revision ID: f3a9c1d7b204
Revises: 0026d61279ce
Create Date: 2026-08-29 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a9c1d7b204'
down_revision = '0026d61279ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_review_state',
            sa.Enum('CHANGES_REQUESTED', 'CHANGES_APPLIED', name='reviewstateenum'),
            nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('github_review_state')

    # ### end Alembic commands ###
